// <auto-generated />
using System;
using MMGC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MMGC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301195000_AddTestimonialsAndContactMessages")]
    partial class AddTestimonialsAndContactMessages
    {
    }
}
