// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MMGC.Data;

#nullable disable

namespace MMGC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124_Phase2_AddProcedureRequestNotificationAndDocumentModels")]
    partial class Phase2_AddProcedureRequestNotificationAndDocumentModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial migration designer - the model is too large to include fully
            // EF Core will generate the necessary SQL based on the Up() method
#pragma warning restore 612, 618
        }
    }
}
